### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by pine3ree** [Templarian/MaterialDesign-Webfont#10]
What about having the original material icons' names added as aliases? 
ex. more_vert => mdi-more-vert

I noticed you are using a list of names and font codes to generate the pseudo elements' content map.
In many occasions i found useful to have sass variables referring to unicode characters so they can be used in other scss files.

ex. $mdi-var-more-vert: '\e5d4'; for the original material design icons

even if your solution saves a lot of space, with a simple script (i used php) a variables file and a pseudo elements icon map file could be generated and this would help with code hinting when using scss variable names.

kind regards

**Comment by Templarian** [comment]
Completely overlooked this issue (sorry I get a lot of GitHub emails and never checked this project for issues since most post them over on the other channel).

Hopefully you found the documentation on getting started. It has a code snippet that does exactly that.

https://materialdesignicons.com/getting-started

**Comment by Templarian** [comment]
Yea, that won't fix the auto-complete in your SASS files, but should make things still pretty readable.

`content: mdi('account');`

In the next release I will most likely be including the `mdi` function in the `_extras.scss` file.
