### ISSUE TITLE
_animated.scss missing

### ISSUE THREAD

**Issue by andersoyvind** [Templarian/MaterialDesign-Webfont#34]
In 1.9.32, materialdesignicons.scss wants to imports _animated.scss (@animated), but it does not exist.

Should it be there, or should the import be removed?

**Comment by jacobq** [comment]
I just ran into this when upgrading to the latest mdi release. In my case, `@import "animated";` seemed to [find font-awesome's `_animated.scss` in my search path](https://github.com/FortAwesome/Font-Awesome/blob/master/scss/_animated.scss), but I hadn't set `$fa-font-path` yet, so this caused me some problems. Importing font-awesome before mdi resolved the problem.

**Comment by Templarian** [comment]
That's a bug in the build process that has been resolved.

Because NPM is both smart and stupid the version is now `v1.9.33`, but for all marketing reasons I'll still call this release `v1.9.32`.

With thousands of you guys using this I need to not do these releases before I go to sleep. Will try and setup a legitimate production release schedule for these.
