### ISSUE TITLE
When will font be updated with the latest added icons?

### ISSUE THREAD

**Issue by kybarg** [Templarian/MaterialDesign-Webfont#5]

**Comment by Templarian** [comment]
Actually 1 more icon till I'm at 50 more. So relatively soon'ish.

**Comment by MilosMosovsky** [comment]
Are you going to update this package ? Or are you open to accept PR's ? Because it wasnt updated for 2 months. Thanks.

**Comment by Templarian** [comment]
@MilosMosovsky It was updated, just never updated this issue.

June 1st was the last build. Just got back from vacation will try and do a build tonight or this week.

The build process is a 1 click action on my side (then a few more seconds to update bower/npm), a pull request wouldn't make sense. :smile:

**Comment by MilosMosovsky** [comment]
nice, but anyways its 1 month. If you have one click update, why we dont
make this full automatic ? :) on every merge to master?

**Comment by Templarian** [comment]
It is definitely being worked on, but there are some large upgrades on the site that are being worked on first. Part of the issue is the font build process is being coded to work with sub packages and icons and multiple icon packs (not just Material Design Icons).

The idea is to have the build process go from database -> webfont (complete) -> github -> bower/npm.

`v1.1.70` is now live on npm/bower and in `master`. Preview it [here](https://cdn.materialdesignicons.com/1.1.70/).

**Comment by ritdaw** [comment]
Any update on this? Could do with a new build.

**Comment by Templarian** [comment]
It is coming out either tonight or tomorrow. There are a few bugs to fix up and issues to close first. Did most of it yesterday though.

**Comment by ritdaw** [comment]
Brilliant, thanks for the quick response!

**Comment by Templarian** [comment]
Launched a couple minutes ago on the site/npm/bower. `v1.2.64`!

Enjoy. Lots of bug fixes.

**Comment by ritdaw** [comment]
Any chance of another update? :) Could do with the updated G icons

**Comment by Templarian** [comment]
I really need to update the font. I actually need a few icons that are not in it now also. Let me do this tonight.

**Comment by ritdaw** [comment]
Much appreciated!

**Comment by Templarian** [comment]
http://cdn.materialdesignicons.com/1.3.41/

**Comment by ritdaw** [comment]
Thanks.
